# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /blog/:title/
#relative_permalinks: true
#permalink: pretty
gems:			  [jekyll-paginate, jekyll-sitemap, jekyll-seo-tag, jekyll-feed]
# Setup
title:               instrumaniak
tagline:             'blog'
description:         'instrumaniak blog'
url:                 https://www.instrumaniak.cf
#baseurl:             '/blog'
paginate:            5
paginate_path: "/blog/page:num/"
excerpt_separator: '<!--more-->'

# About/contact
author:
  name:              Raziur Rahman
  url:               https://twitter.com/instrumaniak
  email:             instrumaniak@gmail.com

# Custom vars
version:             0.6
sass:
  style: :compressed
markdown: kramdown

collections:
  bangla:
    output: true